name: Deployment

on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Release level for the stable version (patch, minor, major)'
        required: false
        type: choice 
        options:   
        - patch
        - minor
        - major
        default: patch

permissions:
  contents: write    
  packages:  write      
  
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:

  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4  
      with:
        fetch-depth: 0

    - name: Bump stable version
      id: bump_stable_tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main
        default_bump: ${{ github.event.inputs.bump_level }}  
        tag_prefix: v
    
    # Enables the runner to emulate different architectures
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Creates a builder instance capable of multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate image metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}       
        tags: |
          type=sha,enable=false
          type=raw,value=latest
          type=raw,value=${{ steps.bump_stable_tag.outputs.new_tag }}

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags:   ${{ steps.meta.outputs.tags }}
        build-args: |
          APP_VERSION=${{ steps.bump_stable_tag.outputs.new_tag }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max,image-manifest=true

    - name: Bump patch and add pre tag
      id: bump_patch
      if: github.ref == 'refs/heads/main'
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: '_NONE_'
        pre_release_branches: main
        default_prerelease_bump: prerelease      
        append_to_pre_release_tag: pre        
        tag_prefix: v
        default_bump: patch